import { createHash } from 'node:crypto';
import { appendFileSync, copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import { fileURLToPath } from 'node:url';
import type { Delta, DeltaEntry, Manifest, ReleaseFile } from '@swept/core';
import { diff } from './export/diff';

/**
 * Turn the freshly built database into a release for the `data` branch:
 * the full database, a delta from the previous release, and a manifest.
 *
 *   pipeline/.prev/   the previous release (checked out by the workflow), if any
 *   pipeline/out/release/   what gets pushed
 *
 * Does nothing when the city's data hasn't changed since the previous release.
 */
const MAX_DELTAS = 26; // half a year of weekly runs; older phones take the full database

const at = (rel: string) => fileURLToPath(new URL(rel, import.meta.url));
const built = at('../out/sides.db');
const prevDir = at('../.prev/');
const outDir = at('../out/release/');

const fileInfo = (dir: string, path: string): ReleaseFile => {
  const bytes = readFileSync(dir + path);
  return { path, md5: createHash('md5').update(bytes).digest('hex'), bytes: bytes.length };
};
const output = (line: string) => process.env.GITHUB_OUTPUT && appendFileSync(process.env.GITHUB_OUTPUT, `${line}\n`);

const prev: Manifest | undefined = existsSync(prevDir + 'manifest.json')
  ? JSON.parse(readFileSync(prevDir + 'manifest.json', 'utf8'))
  : undefined;

const meta = new DatabaseSync(built, { readOnly: true });
const builtAt = (meta.prepare("SELECT value FROM meta WHERE key = 'builtAt'").get() as { value: string }).value;
const sides = (meta.prepare('SELECT count(*) AS n FROM side').get() as { n: number }).n;
meta.close();

const changes = prev ? diff(prevDir + 'sides.db', built) : undefined;
if (prev && changes && changes.upsert.length === 0 && changes.remove.length === 0) {
  console.log(`no change since version ${prev.version}: nothing to release`);
  output('changed=false');
  process.exit(0);
}

const version = (prev?.version ?? 0) + 1;
rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir + 'deltas', { recursive: true });

copyFileSync(built, outDir + 'sides.db');
const stamped = new DatabaseSync(outDir + 'sides.db');
stamped.prepare("UPDATE meta SET value = ? WHERE key = 'version'").run(String(version));
stamped.exec('VACUUM');
stamped.close();

const deltas: DeltaEntry[] = [];
if (prev && changes) {
  // Carry the earlier deltas forward so phones several releases behind can still chain.
  for (const d of prev.deltas.slice(-(MAX_DELTAS - 1))) {
    if (!existsSync(prevDir + d.path)) continue;
    copyFileSync(prevDir + d.path, outDir + d.path);
    deltas.push(d);
  }
  const delta: Delta = { from: prev.version, to: version, builtAt, ...changes };
  const path = `deltas/${prev.version}-${version}.json`;
  writeFileSync(outDir + path, JSON.stringify(delta));
  deltas.push({ from: prev.version, to: version, ...fileInfo(outDir, path) });
  console.log(`delta ${prev.version} → ${version}: ${changes.upsert.length} sides changed, ${changes.remove.length} removed (${(statSync(outDir + path).size / 1024).toFixed(1)} KB)`);
}

const manifest: Manifest = { version, builtAt, sides, full: fileInfo(outDir, 'sides.db'), deltas };
writeFileSync(outDir + 'manifest.json', `${JSON.stringify(manifest, null, 2)}\n`);
writeFileSync(
  outDir + 'README.md',
  `# Swept street data\n\nGenerated by the "Refresh street data" workflow from Ville de Montréal open data.\nVersion ${version}, built ${builtAt}. Do not edit: this branch is overwritten on every release.\n`,
);
console.log(`release ${version}: ${sides} sides, sides.db ${(manifest.full.bytes / 1e6).toFixed(1)} MB, ${deltas.length} delta(s)`);
output('changed=true');
output(`version=${version}`);
